# Encapsulation

# Abstraction

# Inheritance

# Polymorphism


In [2]:
#single inheritance

class Animal:
    def __init__(self, name, age):
        self.name = name
        self.age =  age

class Dog(Animal): #Animal is parent of Dog
    def __init__(self, color, food, name, age):
        self.color = color
        self.food = food
        super().__init__(name,age) #inherit the constructor from parent class **********
        print(self.color, self.food, self.name, self.age)
        
    def display(self):
        print(self.color, self.food, self.name, self.age)

objDog = Dog("brown","meat","Candy","2")
objDog.display()
        

    

brown meat Candy 2
brown meat Candy 2


In [3]:
#Hierarchical  inheritance

class Animal:
    def __init__(self, name, age):
        self.name = name
        self.age =  age

class Dog(Animal): #Animal is parent of Dog
    def __init__(self, color, food, name, age):
        self.color = color
        self.food = food
        super().__init__(name,age) #inherit the constructor from parent class **********
        #print(self.color, self.food, self.name, self.age)
        
    def display(self):
        print(self.color, self.food, self.name, self.age)

class Cat(Animal): #Animal is parent of Dog
    def __init__(self, color, food, name, age):
        self.color = color
        self.food = food
        super().__init__(name,age) #inherit the constructor from parent class **********
        #print(self.color, self.food, self.name, self.age)
        
    def display(self):
        print(self.color, self.food, self.name, self.age)

objDog = Dog("brown","meat","Candy","2")
objDog.display()

objCat = Cat("white","milk","Miky","1")
objCat.display()


brown meat Candy 2
white milk Miky 1


# 29 Nov 2024 Polymorphism


Overriding

In [6]:
class Animal:
    def __init__(self, name, age):
        self.name = name
        self.age =  age
    def fun(self):
        print("parent class function FUN")

class Dog(Animal): #Animal is parent of Dog
    def __init__(self, color, food, name, age):
        self.color = color
        self.food = food
        super().__init__(name,age) #inherit the constructor from parent class **********
        
    def display(self):
        print(self.color, self.food, self.name, self.age)

    def fun(self):
        print("Child class class function FUN")


objDog = Dog("brown","meat","Candy","2")
objDog.fun()


Child class class function FUN


In [17]:
#abstract base class and abstract methods  #overloading

from abc import ABC, abstractmethod  #ABC = Abstract Base Class
class Pet(ABC): # this is an abstract base class    
    @abstractmethod
    def breed(self):# this is an abstract method
        pass

class Dog(Pet): #Animal is parent of Dog    
    def __init__(self, color, food, name, age):
        self.color = color
        self.food = food
       
    def display(self):
        print(self.color, self.food, self.name, self.age)

    def fun(self):
        print("Child class class function FUN")

    def breed(self):
        print("I belong to the child class Dog")


objDog = Dog("brown","meat","Candy","2")
objDog.fun()
objDog.breed()

Child class class function FUN
I belong to the child class Dog


In [10]:
class Pets(): # this is an abstract base class    
    @abstractmethod
    def breed(self):# this is an abstract method
        pass

class Dog(Pets): #Animal is parent of Dog    
    def __init__(self, color, food, name, age):
        self.color = color
        self.food = food
       
    def display(self):
        print(self.color, self.food, self.name, self.age)

    def fun(self):
        print("Child class class function FUN")

    def breed(self):
        print("I belong to the child class Dog")


objDog = Dog("brown","meat","Candy","2")
objDog.fun()
objDog.breed()

Child class class function FUN
I belong to the child class Dog


# Access specifiers
# private  __abc

# protected _abc

# public  abc

In [33]:
import numpy as np

#array([2, 2, 9]) # random
print(np.random.randint(1, [3, 5, 10]))
print(np.random.randint(1,size=5))
print(np.random.randint(1,size=5))

[1 3 7]
[0 0 0 0 0]
[0 0 0 0 0]


In [39]:
import random 

for i in range(5):
    print(random.randint(1,20))

12
5
8
6
15


# S7 Practice
# 29 Nov2024 ,  01:02 BRT

task 1: multi leve is parent 1 - child 1 (super.init)- subchild 1  (super.init)
task 2: parent1 (ABC)  -- child 1, parent1 (ABC)  -- child 2

task1 - product(ABC) + method:pass
task2: concrete meaning object created >> >> 2 child class 1. digital rpduct 2. physical product ,  method>> redefine in cal_total_proce

task 3 -
task 4 -

task 5 - main() >> put objts +method